-
  name: Deploy a web application
  hosts: db_and_web_server*
  become_user: root
  become: yes
  tasks:
    - command: /pathtoscript/script-web.py
      async: 360
      poll: 60

# in here we are blocked , waiting 360 seconds for the first script to complete

    - command: /pathtoscript/script-db.py
      async: 360
      poll: 60

  #  - name:
  #  - name: 