-
  name: Deploy a web application
  hosts: db_and_web_server*
  become_user: root
  become: yes

  tasks:
  
    - name: Install dependencies
      apt:  
        name: ['python', 'python-setuptools', 'python-dev', 'build-essential', 'python-pip', 'python-mysqldb']
        state: present

    - include: tasks/deploy_db.yaml

    - include: tasks/deploy_web.yaml

    - include: tasks/destroy.yaml
