-
  name: mail 
  hosts: db_and_web_server*
  become_user: root
  become: yes

  tasks:
  
    - name: "Send notification email"
      mail:
        to: devops@corp.com
        subject: Server Deployed!
        body: Web Server Deployed Successfully
      ignore_errors: yes

    - command: cat /path/file.log
      register: command_output
      failed_when: "'ERROR' in command_output.stdout"